//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionInformationType", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    [System.SerializableAttribute()]
    public partial class SubscriptionInformationType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long subscriptionidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        private System.DateTime createdField;
        
        private int expmonthField;
        
        private int expyearField;
        
        private EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.CardType cardtypeidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.TransactionInformationType[] transactionListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long subscriptionid {
            get {
                return this.subscriptionidField;
            }
            set {
                if ((this.subscriptionidField.Equals(value) != true)) {
                    this.subscriptionidField = value;
                    this.RaisePropertyChanged("subscriptionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                if ((this.createdField.Equals(value) != true)) {
                    this.createdField = value;
                    this.RaisePropertyChanged("created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int expmonth {
            get {
                return this.expmonthField;
            }
            set {
                if ((this.expmonthField.Equals(value) != true)) {
                    this.expmonthField = value;
                    this.RaisePropertyChanged("expmonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int expyear {
            get {
                return this.expyearField;
            }
            set {
                if ((this.expyearField.Equals(value) != true)) {
                    this.expyearField = value;
                    this.RaisePropertyChanged("expyear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.CardType cardtypeid {
            get {
                return this.cardtypeidField;
            }
            set {
                if ((this.cardtypeidField.Equals(value) != true)) {
                    this.cardtypeidField = value;
                    this.RaisePropertyChanged("cardtypeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.TransactionInformationType[] transactionList {
            get {
                return this.transactionListField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionListField, value) != true)) {
                    this.transactionListField = value;
                    this.RaisePropertyChanged("transactionList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardType", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public enum CardType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DANKORT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VISA_DANKORT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VISA_ELECTRON_FOREIGN = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MASTERCARD = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MASTERCARD_FOREIGN = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VISA_ELECTRON = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JCB = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DINERS = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAESTRO = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMERICAN_EXPRESS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EDK = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DINERS_FOREIGN = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMERICAN_EXPRESS_FOREIGN = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAESTRO_FOREIGN = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FORBRUGSFORENINGEN = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EWIRE = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VISA = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IKANO = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHERS = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORDEA_SOLO = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DANSKE_BANK = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BG_BANK = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LIC_MASTERCARD = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LIC_MASTERCARD_FOREIGN = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYPAL = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOBILPENGE = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KLARNA = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVEA = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEB_DIREKTBETALNINGAR = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORDEA_SE_DIREKTBETALNING = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HANDELSBANKEN_SE_DIREKTBETALNINGAR = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWEDBANK_DIREKTBETALNINGAR = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IBILL = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEMPAY = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDEAL = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLEARHAUS = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MASTERPASS = 38,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionInformationType", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    [System.SerializableAttribute()]
    public partial class TransactionInformationType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupField;
        
        private int authamountField;
        
        private int currencyField;
        
        private int cardtypeidField;
        
        private int capturedamountField;
        
        private int creditedamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        private System.DateTime authdateField;
        
        private System.DateTime captureddateField;
        
        private System.DateTime deleteddateField;
        
        private System.DateTime crediteddateField;
        
        private EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.TransactionStatus statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.TransactionHistoryInfo[] historyField;
        
        private long transactionidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cardholderField;
        
        private EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.PayMode modeField;
        
        private bool mscField;
        
        private int fraudStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FraudMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payerCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string issuedCountryCodeField;
        
        private int feeField;
        
        private bool splitpaymentField;
        
        private EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.AcquirerType acquirerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tcardnoField;
        
        private int expmonthField;
        
        private int expyearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string group {
            get {
                return this.groupField;
            }
            set {
                if ((object.ReferenceEquals(this.groupField, value) != true)) {
                    this.groupField = value;
                    this.RaisePropertyChanged("group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int authamount {
            get {
                return this.authamountField;
            }
            set {
                if ((this.authamountField.Equals(value) != true)) {
                    this.authamountField = value;
                    this.RaisePropertyChanged("authamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int currency {
            get {
                return this.currencyField;
            }
            set {
                if ((this.currencyField.Equals(value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int cardtypeid {
            get {
                return this.cardtypeidField;
            }
            set {
                if ((this.cardtypeidField.Equals(value) != true)) {
                    this.cardtypeidField = value;
                    this.RaisePropertyChanged("cardtypeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int capturedamount {
            get {
                return this.capturedamountField;
            }
            set {
                if ((this.capturedamountField.Equals(value) != true)) {
                    this.capturedamountField = value;
                    this.RaisePropertyChanged("capturedamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int creditedamount {
            get {
                return this.creditedamountField;
            }
            set {
                if ((this.creditedamountField.Equals(value) != true)) {
                    this.creditedamountField = value;
                    this.RaisePropertyChanged("creditedamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                if ((object.ReferenceEquals(this.orderidField, value) != true)) {
                    this.orderidField = value;
                    this.RaisePropertyChanged("orderid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime authdate {
            get {
                return this.authdateField;
            }
            set {
                if ((this.authdateField.Equals(value) != true)) {
                    this.authdateField = value;
                    this.RaisePropertyChanged("authdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime captureddate {
            get {
                return this.captureddateField;
            }
            set {
                if ((this.captureddateField.Equals(value) != true)) {
                    this.captureddateField = value;
                    this.RaisePropertyChanged("captureddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime deleteddate {
            get {
                return this.deleteddateField;
            }
            set {
                if ((this.deleteddateField.Equals(value) != true)) {
                    this.deleteddateField = value;
                    this.RaisePropertyChanged("deleteddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime crediteddate {
            get {
                return this.crediteddateField;
            }
            set {
                if ((this.crediteddateField.Equals(value) != true)) {
                    this.crediteddateField = value;
                    this.RaisePropertyChanged("crediteddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.TransactionStatus status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.TransactionHistoryInfo[] history {
            get {
                return this.historyField;
            }
            set {
                if ((object.ReferenceEquals(this.historyField, value) != true)) {
                    this.historyField = value;
                    this.RaisePropertyChanged("history");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public long transactionid {
            get {
                return this.transactionidField;
            }
            set {
                if ((this.transactionidField.Equals(value) != true)) {
                    this.transactionidField = value;
                    this.RaisePropertyChanged("transactionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string cardholder {
            get {
                return this.cardholderField;
            }
            set {
                if ((object.ReferenceEquals(this.cardholderField, value) != true)) {
                    this.cardholderField = value;
                    this.RaisePropertyChanged("cardholder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.PayMode mode {
            get {
                return this.modeField;
            }
            set {
                if ((this.modeField.Equals(value) != true)) {
                    this.modeField = value;
                    this.RaisePropertyChanged("mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool msc {
            get {
                return this.mscField;
            }
            set {
                if ((this.mscField.Equals(value) != true)) {
                    this.mscField = value;
                    this.RaisePropertyChanged("msc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int fraudStatus {
            get {
                return this.fraudStatusField;
            }
            set {
                if ((this.fraudStatusField.Equals(value) != true)) {
                    this.fraudStatusField = value;
                    this.RaisePropertyChanged("fraudStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string FraudMessage {
            get {
                return this.FraudMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FraudMessageField, value) != true)) {
                    this.FraudMessageField = value;
                    this.RaisePropertyChanged("FraudMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string payerCountryCode {
            get {
                return this.payerCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.payerCountryCodeField, value) != true)) {
                    this.payerCountryCodeField = value;
                    this.RaisePropertyChanged("payerCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string issuedCountryCode {
            get {
                return this.issuedCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.issuedCountryCodeField, value) != true)) {
                    this.issuedCountryCodeField = value;
                    this.RaisePropertyChanged("issuedCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int fee {
            get {
                return this.feeField;
            }
            set {
                if ((this.feeField.Equals(value) != true)) {
                    this.feeField = value;
                    this.RaisePropertyChanged("fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public bool splitpayment {
            get {
                return this.splitpaymentField;
            }
            set {
                if ((this.splitpaymentField.Equals(value) != true)) {
                    this.splitpaymentField = value;
                    this.RaisePropertyChanged("splitpayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.AcquirerType acquirer {
            get {
                return this.acquirerField;
            }
            set {
                if ((this.acquirerField.Equals(value) != true)) {
                    this.acquirerField = value;
                    this.RaisePropertyChanged("acquirer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string tcardno {
            get {
                return this.tcardnoField;
            }
            set {
                if ((object.ReferenceEquals(this.tcardnoField, value) != true)) {
                    this.tcardnoField = value;
                    this.RaisePropertyChanged("tcardno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public int expmonth {
            get {
                return this.expmonthField;
            }
            set {
                if ((this.expmonthField.Equals(value) != true)) {
                    this.expmonthField = value;
                    this.RaisePropertyChanged("expmonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public int expyear {
            get {
                return this.expyearField;
            }
            set {
                if ((this.expyearField.Equals(value) != true)) {
                    this.expyearField = value;
                    this.RaisePropertyChanged("expyear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatus", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public enum TransactionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_UNDEFINED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_NEW = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_CAPTURED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_DELETED = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_INSTANT_CAPTURE_FAILED = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_SUBSCRIPTION_INI = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_RENEW = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_EUROLINE_WAIT_CAPTURE = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYMENT_EUROLINE_WAIT_CREDIT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PARTLY_TRANSACTION_HIDDEN = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionHistoryInfo", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    [System.SerializableAttribute()]
    public partial class TransactionHistoryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long transactionHistoryIDField;
        
        private int logonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eventMsgField;
        
        private System.DateTime createdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long transactionHistoryID {
            get {
                return this.transactionHistoryIDField;
            }
            set {
                if ((this.transactionHistoryIDField.Equals(value) != true)) {
                    this.transactionHistoryIDField = value;
                    this.RaisePropertyChanged("transactionHistoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int logonID {
            get {
                return this.logonIDField;
            }
            set {
                if ((this.logonIDField.Equals(value) != true)) {
                    this.logonIDField = value;
                    this.RaisePropertyChanged("logonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string eventMsg {
            get {
                return this.eventMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.eventMsgField, value) != true)) {
                    this.eventMsgField = value;
                    this.RaisePropertyChanged("eventMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                if ((this.createdField.Equals(value) != true)) {
                    this.createdField = value;
                    this.RaisePropertyChanged("created");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayMode", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public enum PayMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MODE_PRODUCTION = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MODE_TEST = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MODE_EPAY = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcquirerType", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public enum AcquirerType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PBS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUROLINE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DANSKE_BANK = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORDEA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EWIRE = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWEDBANK = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYPAL = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BABS_SWEDBANK = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOBILPENGE = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KLARNA = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVEA = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HANDELSBANKEN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEB_DIREKT = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORDEA_SE_DIREKT = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HANDELSBANKEN_DIREKT = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWEDBANK_DIREKT = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IBILL = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEMPAY = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDEAL = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OBETUR = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_NORDEA_SE = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_NORDEA_DK = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_NORDEA_NO = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_NORDEA_FI = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MERCHANT4T = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_HANDELSBANKEN_SE = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_HANDELSBANKEN_DK = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_HANDELSBANKEN_NO = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_HANDELSBANKEN_FI = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_ELAVON = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_SWEDBANK = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_EUROLINE = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVRY_TELLER = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VALITOR = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLEARHAUS = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESURS_BANK = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EKSPRES_BANK = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWIPP = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MASTERPASS = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAMBORA = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EPAY = 41,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", ConfigurationName="epaySubscriptionService.SubscriptionSoap")]
    public interface SubscriptionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/deletesubscription", ReplyAction="*")]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponse deletesubscription(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/deletesubscription", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponse> deletesubscriptionAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/authorize", ReplyAction="*")]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponse authorize(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponse> authorizeAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getsubscriptions", ReplyAction="*")]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponse getsubscriptions(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getsubscriptions", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponse> getsubscriptionsAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getsubscription_byids" +
            "", ReplyAction="*")]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponse getsubscription_byids(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getsubscription_byids" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponse> getsubscription_byidsAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getPbsError", ReplyAction="*")]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponse getPbsError(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getPbsError", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponse> getPbsErrorAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getEpayError", ReplyAction="*")]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponse getEpayError(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssl.ditonlinebetalingssystem.dk/remote/subscription/getEpayError", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponse> getEpayErrorAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletesubscriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletesubscription", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequestBody Body;
        
        public deletesubscriptionRequest() {
        }
        
        public deletesubscriptionRequest(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class deletesubscriptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long subscriptionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int epayresponse;
        
        public deletesubscriptionRequestBody() {
        }
        
        public deletesubscriptionRequestBody(int merchantnumber, long subscriptionid, string pwd, int epayresponse) {
            this.merchantnumber = merchantnumber;
            this.subscriptionid = subscriptionid;
            this.pwd = pwd;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletesubscriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletesubscriptionResponse", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponseBody Body;
        
        public deletesubscriptionResponse() {
        }
        
        public deletesubscriptionResponse(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class deletesubscriptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool deletesubscriptionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int epayresponse;
        
        public deletesubscriptionResponseBody() {
        }
        
        public deletesubscriptionResponseBody(bool deletesubscriptionResult, int epayresponse) {
            this.deletesubscriptionResult = deletesubscriptionResult;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authorize", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequestBody Body;
        
        public authorizeRequest() {
        }
        
        public authorizeRequest(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class authorizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long subscriptionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int currency;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int instantcapture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string group;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sms;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ipaddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string textonstatement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string customerkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int fraud;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public long transactionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int pbsresponse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public int epayresponse;
        
        public authorizeRequestBody() {
        }
        
        public authorizeRequestBody(
                    int merchantnumber, 
                    long subscriptionid, 
                    string orderid, 
                    int amount, 
                    int currency, 
                    int instantcapture, 
                    string group, 
                    string description, 
                    string email, 
                    string sms, 
                    string ipaddress, 
                    string pwd, 
                    string textonstatement, 
                    string customerkey, 
                    int fraud, 
                    long transactionid, 
                    int pbsresponse, 
                    int epayresponse) {
            this.merchantnumber = merchantnumber;
            this.subscriptionid = subscriptionid;
            this.orderid = orderid;
            this.amount = amount;
            this.currency = currency;
            this.instantcapture = instantcapture;
            this.group = group;
            this.description = description;
            this.email = email;
            this.sms = sms;
            this.ipaddress = ipaddress;
            this.pwd = pwd;
            this.textonstatement = textonstatement;
            this.customerkey = customerkey;
            this.fraud = fraud;
            this.transactionid = transactionid;
            this.pbsresponse = pbsresponse;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authorizeResponse", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponseBody Body;
        
        public authorizeResponse() {
        }
        
        public authorizeResponse(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class authorizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool authorizeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int fraud;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long transactionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pbsresponse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int epayresponse;
        
        public authorizeResponseBody() {
        }
        
        public authorizeResponseBody(bool authorizeResult, int fraud, long transactionid, int pbsresponse, int epayresponse) {
            this.authorizeResult = authorizeResult;
            this.fraud = fraud;
            this.transactionid = transactionid;
            this.pbsresponse = pbsresponse;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsubscriptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getsubscriptions", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequestBody Body;
        
        public getsubscriptionsRequest() {
        }
        
        public getsubscriptionsRequest(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getsubscriptionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long subscriptionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionInformationType[] subscriptionAry;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int epayresponse;
        
        public getsubscriptionsRequestBody() {
        }
        
        public getsubscriptionsRequestBody(int merchantnumber, long subscriptionid, string pwd, EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionInformationType[] subscriptionAry, int epayresponse) {
            this.merchantnumber = merchantnumber;
            this.subscriptionid = subscriptionid;
            this.pwd = pwd;
            this.subscriptionAry = subscriptionAry;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsubscriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getsubscriptionsResponse", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponseBody Body;
        
        public getsubscriptionsResponse() {
        }
        
        public getsubscriptionsResponse(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getsubscriptionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool getsubscriptionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionInformationType[] subscriptionAry;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int epayresponse;
        
        public getsubscriptionsResponseBody() {
        }
        
        public getsubscriptionsResponseBody(bool getsubscriptionsResult, EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionInformationType[] subscriptionAry, int epayresponse) {
            this.getsubscriptionsResult = getsubscriptionsResult;
            this.subscriptionAry = subscriptionAry;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsubscription_byidsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getsubscription_byids", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequestBody Body;
        
        public getsubscription_byidsRequest() {
        }
        
        public getsubscription_byidsRequest(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getsubscription_byidsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.ArrayOfLong subscription_ids;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int epayresponse;
        
        public getsubscription_byidsRequestBody() {
        }
        
        public getsubscription_byidsRequestBody(int merchantnumber, string pwd, EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.ArrayOfLong subscription_ids, int epayresponse) {
            this.merchantnumber = merchantnumber;
            this.pwd = pwd;
            this.subscription_ids = subscription_ids;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsubscription_byidsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getsubscription_byidsResponse", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponseBody Body;
        
        public getsubscription_byidsResponse() {
        }
        
        public getsubscription_byidsResponse(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getsubscription_byidsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool getsubscription_byidsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.ArrayOfLong subscription_ids;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int epayresponse;
        
        public getsubscription_byidsResponseBody() {
        }
        
        public getsubscription_byidsResponseBody(bool getsubscription_byidsResult, EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.ArrayOfLong subscription_ids, int epayresponse) {
            this.getsubscription_byidsResult = getsubscription_byidsResult;
            this.subscription_ids = subscription_ids;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPbsErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPbsError", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequestBody Body;
        
        public getPbsErrorRequest() {
        }
        
        public getPbsErrorRequest(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getPbsErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int language;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pbsResponseCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pbsResponseString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int epayresponse;
        
        public getPbsErrorRequestBody() {
        }
        
        public getPbsErrorRequestBody(int merchantnumber, int language, int pbsResponseCode, string pwd, string pbsResponseString, int epayresponse) {
            this.merchantnumber = merchantnumber;
            this.language = language;
            this.pbsResponseCode = pbsResponseCode;
            this.pwd = pwd;
            this.pbsResponseString = pbsResponseString;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPbsErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPbsErrorResponse", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponseBody Body;
        
        public getPbsErrorResponse() {
        }
        
        public getPbsErrorResponse(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getPbsErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool getPbsErrorResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pbsResponseString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int epayresponse;
        
        public getPbsErrorResponseBody() {
        }
        
        public getPbsErrorResponseBody(bool getPbsErrorResult, string pbsResponseString, int epayresponse) {
            this.getPbsErrorResult = getPbsErrorResult;
            this.pbsResponseString = pbsResponseString;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEpayErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEpayError", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequestBody Body;
        
        public getEpayErrorRequest() {
        }
        
        public getEpayErrorRequest(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getEpayErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int language;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int epayresponsecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string epayResponseString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int epayresponse;
        
        public getEpayErrorRequestBody() {
        }
        
        public getEpayErrorRequestBody(int merchantnumber, int language, int epayresponsecode, string pwd, string epayResponseString, int epayresponse) {
            this.merchantnumber = merchantnumber;
            this.language = language;
            this.epayresponsecode = epayresponsecode;
            this.pwd = pwd;
            this.epayResponseString = epayResponseString;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEpayErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEpayErrorResponse", Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription", Order=0)]
        public EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponseBody Body;
        
        public getEpayErrorResponse() {
        }
        
        public getEpayErrorResponse(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssl.ditonlinebetalingssystem.dk/remote/subscription")]
    public partial class getEpayErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool getEpayErrorResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string epayResponseString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int epayresponse;
        
        public getEpayErrorResponseBody() {
        }
        
        public getEpayErrorResponseBody(bool getEpayErrorResult, string epayResponseString, int epayresponse) {
            this.getEpayErrorResult = getEpayErrorResult;
            this.epayResponseString = epayResponseString;
            this.epayresponse = epayresponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubscriptionSoapChannel : EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriptionSoapClient : System.ServiceModel.ClientBase<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap>, EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap {
        
        public SubscriptionSoapClient() {
        }
        
        public SubscriptionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriptionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponse EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.deletesubscription(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest request) {
            return base.Channel.deletesubscription(request);
        }
        
        public bool deletesubscription(int merchantnumber, long subscriptionid, string pwd, ref int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.subscriptionid = subscriptionid;
            inValue.Body.pwd = pwd;
            inValue.Body.epayresponse = epayresponse;
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponse retVal = ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).deletesubscription(inValue);
            epayresponse = retVal.Body.epayresponse;
            return retVal.Body.deletesubscriptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponse> EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.deletesubscriptionAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest request) {
            return base.Channel.deletesubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionResponse> deletesubscriptionAsync(int merchantnumber, long subscriptionid, string pwd, int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.deletesubscriptionRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.subscriptionid = subscriptionid;
            inValue.Body.pwd = pwd;
            inValue.Body.epayresponse = epayresponse;
            return ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).deletesubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponse EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.authorize(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest request) {
            return base.Channel.authorize(request);
        }
        
        public bool authorize(
                    int merchantnumber, 
                    long subscriptionid, 
                    string orderid, 
                    int amount, 
                    int currency, 
                    int instantcapture, 
                    string group, 
                    string description, 
                    string email, 
                    string sms, 
                    string ipaddress, 
                    string pwd, 
                    string textonstatement, 
                    string customerkey, 
                    ref int fraud, 
                    ref long transactionid, 
                    ref int pbsresponse, 
                    ref int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.subscriptionid = subscriptionid;
            inValue.Body.orderid = orderid;
            inValue.Body.amount = amount;
            inValue.Body.currency = currency;
            inValue.Body.instantcapture = instantcapture;
            inValue.Body.group = group;
            inValue.Body.description = description;
            inValue.Body.email = email;
            inValue.Body.sms = sms;
            inValue.Body.ipaddress = ipaddress;
            inValue.Body.pwd = pwd;
            inValue.Body.textonstatement = textonstatement;
            inValue.Body.customerkey = customerkey;
            inValue.Body.fraud = fraud;
            inValue.Body.transactionid = transactionid;
            inValue.Body.pbsresponse = pbsresponse;
            inValue.Body.epayresponse = epayresponse;
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponse retVal = ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).authorize(inValue);
            fraud = retVal.Body.fraud;
            transactionid = retVal.Body.transactionid;
            pbsresponse = retVal.Body.pbsresponse;
            epayresponse = retVal.Body.epayresponse;
            return retVal.Body.authorizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponse> EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.authorizeAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest request) {
            return base.Channel.authorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeResponse> authorizeAsync(
                    int merchantnumber, 
                    long subscriptionid, 
                    string orderid, 
                    int amount, 
                    int currency, 
                    int instantcapture, 
                    string group, 
                    string description, 
                    string email, 
                    string sms, 
                    string ipaddress, 
                    string pwd, 
                    string textonstatement, 
                    string customerkey, 
                    int fraud, 
                    long transactionid, 
                    int pbsresponse, 
                    int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.authorizeRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.subscriptionid = subscriptionid;
            inValue.Body.orderid = orderid;
            inValue.Body.amount = amount;
            inValue.Body.currency = currency;
            inValue.Body.instantcapture = instantcapture;
            inValue.Body.group = group;
            inValue.Body.description = description;
            inValue.Body.email = email;
            inValue.Body.sms = sms;
            inValue.Body.ipaddress = ipaddress;
            inValue.Body.pwd = pwd;
            inValue.Body.textonstatement = textonstatement;
            inValue.Body.customerkey = customerkey;
            inValue.Body.fraud = fraud;
            inValue.Body.transactionid = transactionid;
            inValue.Body.pbsresponse = pbsresponse;
            inValue.Body.epayresponse = epayresponse;
            return ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).authorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponse EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getsubscriptions(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest request) {
            return base.Channel.getsubscriptions(request);
        }
        
        public bool getsubscriptions(int merchantnumber, long subscriptionid, string pwd, ref EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionInformationType[] subscriptionAry, ref int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.subscriptionid = subscriptionid;
            inValue.Body.pwd = pwd;
            inValue.Body.subscriptionAry = subscriptionAry;
            inValue.Body.epayresponse = epayresponse;
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponse retVal = ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getsubscriptions(inValue);
            subscriptionAry = retVal.Body.subscriptionAry;
            epayresponse = retVal.Body.epayresponse;
            return retVal.Body.getsubscriptionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponse> EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getsubscriptionsAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest request) {
            return base.Channel.getsubscriptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsResponse> getsubscriptionsAsync(int merchantnumber, long subscriptionid, string pwd, EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionInformationType[] subscriptionAry, int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscriptionsRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.subscriptionid = subscriptionid;
            inValue.Body.pwd = pwd;
            inValue.Body.subscriptionAry = subscriptionAry;
            inValue.Body.epayresponse = epayresponse;
            return ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getsubscriptionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponse EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getsubscription_byids(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest request) {
            return base.Channel.getsubscription_byids(request);
        }
        
        public bool getsubscription_byids(int merchantnumber, string pwd, ref EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.ArrayOfLong subscription_ids, ref int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.pwd = pwd;
            inValue.Body.subscription_ids = subscription_ids;
            inValue.Body.epayresponse = epayresponse;
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponse retVal = ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getsubscription_byids(inValue);
            subscription_ids = retVal.Body.subscription_ids;
            epayresponse = retVal.Body.epayresponse;
            return retVal.Body.getsubscription_byidsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponse> EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getsubscription_byidsAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest request) {
            return base.Channel.getsubscription_byidsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsResponse> getsubscription_byidsAsync(int merchantnumber, string pwd, EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.ArrayOfLong subscription_ids, int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getsubscription_byidsRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.pwd = pwd;
            inValue.Body.subscription_ids = subscription_ids;
            inValue.Body.epayresponse = epayresponse;
            return ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getsubscription_byidsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponse EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getPbsError(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest request) {
            return base.Channel.getPbsError(request);
        }
        
        public bool getPbsError(int merchantnumber, int language, int pbsResponseCode, string pwd, ref string pbsResponseString, ref int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.language = language;
            inValue.Body.pbsResponseCode = pbsResponseCode;
            inValue.Body.pwd = pwd;
            inValue.Body.pbsResponseString = pbsResponseString;
            inValue.Body.epayresponse = epayresponse;
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponse retVal = ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getPbsError(inValue);
            pbsResponseString = retVal.Body.pbsResponseString;
            epayresponse = retVal.Body.epayresponse;
            return retVal.Body.getPbsErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponse> EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getPbsErrorAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest request) {
            return base.Channel.getPbsErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorResponse> getPbsErrorAsync(int merchantnumber, int language, int pbsResponseCode, string pwd, string pbsResponseString, int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getPbsErrorRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.language = language;
            inValue.Body.pbsResponseCode = pbsResponseCode;
            inValue.Body.pwd = pwd;
            inValue.Body.pbsResponseString = pbsResponseString;
            inValue.Body.epayresponse = epayresponse;
            return ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getPbsErrorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponse EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getEpayError(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest request) {
            return base.Channel.getEpayError(request);
        }
        
        public bool getEpayError(int merchantnumber, int language, int epayresponsecode, string pwd, ref string epayResponseString, ref int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.language = language;
            inValue.Body.epayresponsecode = epayresponsecode;
            inValue.Body.pwd = pwd;
            inValue.Body.epayResponseString = epayResponseString;
            inValue.Body.epayresponse = epayresponse;
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponse retVal = ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getEpayError(inValue);
            epayResponseString = retVal.Body.epayResponseString;
            epayresponse = retVal.Body.epayresponse;
            return retVal.Body.getEpayErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponse> EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap.getEpayErrorAsync(EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest request) {
            return base.Channel.getEpayErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorResponse> getEpayErrorAsync(int merchantnumber, int language, int epayresponsecode, string pwd, string epayResponseString, int epayresponse) {
            EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest inValue = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequest();
            inValue.Body = new EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.getEpayErrorRequestBody();
            inValue.Body.merchantnumber = merchantnumber;
            inValue.Body.language = language;
            inValue.Body.epayresponsecode = epayresponsecode;
            inValue.Body.pwd = pwd;
            inValue.Body.epayResponseString = epayResponseString;
            inValue.Body.epayresponse = epayresponse;
            return ((EPiServer.Business.Commerce.Payment.Valtech.Epay.epaySubscriptionService.SubscriptionSoap)(this)).getEpayErrorAsync(inValue);
        }
    }
}
